'use client';

import { useState } from 'react';
import { Turnstile } from '@marsidev/react-turnstile';
import { useRouter } from 'next/navigation';

export default function HomePage() {
  const [zaloName, setZaloName] = useState('');
    const [turnstileToken, setTurnstileToken] = useState<string | null>(null);
      const [loading, setLoading] = useState(false);
        const router = useRouter();

          const handleSubmit = async (e: React.FormEvent) => {
              e.preventDefault();
                  if (!turnstileToken || !zaloName.trim()) return;
                      setLoading(true);
                          try {
                                const res = await fetch('/api/generate-link', {
                                        method: 'POST',
                                                headers: { 'Content-Type': 'application/json' },
                                                        body: JSON.stringify({ zaloName: zaloName.trim(), turnstileToken }),
                                                              });
                                                                    if (!res.ok) {
                                                                            const errorData = await res.json();
                                                                                    alert(errorData.error || 'Có lỗi xảy ra');
                                                                                            return;
                                                                                                  }
                                                                                                        const data = await res.json();
                                                                                                              if (data.link) {
                                                                                                                      window.location.href = data.link; // Chuyển hướng sang link rút gọn
                                                                                                                            } else {
                                                                                                                                    alert('Không nhận được link rút gọn');
                                                                                                                                          }
                                                                                                                                              } catch (error) {
                                                                                                                                                    alert('Lỗi kết nối');
                                                                                                                                                        } finally {
                                                                                                                                                              setLoading(false);
                                                                                                                                                                  }
                                                                                                                                                                    };

                                                                                                                                                                      return (
                                                                                                                                                                          <main className="min-h-screen flex items-center justify-center bg-gray-50">
                                                                                                                                                                                <div className="max-w-md w-full bg-white rounded-lg shadow-lg p-8">
                                                                                                                                                                                        <h1 className="text-2xl font-bold text-center text-gray-800 mb-6">
                                                                                                                                                                                                  Xác thực thành viên nhóm Zalo
                                                                                                                                                                                                          </h1>
                                                                                                                                                                                                                  <form onSubmit={handleSubmit} className="space-y-4">
                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                        <label htmlFor="zaloName" className="block text-sm font-medium text-gray-700">
                                                                                                                                                                                                                                                      Tên Zalo của bạn
                                                                                                                                                                                                                                                                  </label>
                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                            id="zaloName"
                                                                                                                                                                                                                                                                                                          type="text"
                                                                                                                                                                                                                                                                                                                        value={zaloName}
                                                                                                                                                                                                                                                                                                                                      onChange={(e) => setZaloName(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                    className="mt-1 block w-full border border-gray-300 rounded-md shadow-sm p-2 focus:ring-blue-500 focus:border-blue-500"
                                                                                                                                                                                                                                                                                                                                                                  placeholder="Nhập tên Zalo"
                                                                                                                                                                                                                                                                                                                                                                                required
                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex justify-center">
                                                                                                                                                                                                                                                                                                                                                                                                                            <Turnstile
                                                                                                                                                                                                                                                                                                                                                                                                                                          siteKey={process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY!}
                                                                                                                                                                                                                                                                                                                                                                                                                                                        onSuccess={(token) => setTurnstileToken(token)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onError={() => setTurnstileToken(null)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onExpire={() => setTurnstileToken(null)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            disabled={!turnstileToken || loading || !zaloName.trim()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 disabled:bg-gray-400 disabled:cursor-not-allowed"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {loading ? 'Đang xử lý...' : 'Lấy Mã Xác Thực'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }