'use client';

import { useEffect, useState, Suspense } from 'react';
import { useSearchParams } from 'next/navigation';

// ⚠️ Bắt buộc phải render động trên Vercel để bắt đúng query parameter
export const dynamic = 'force-dynamic';

function GetCodeContent() {
  const searchParams = useSearchParams();
    const userId = searchParams.get('user_id');
      const [loading, setLoading] = useState(true);
        const [code, setCode] = useState<string | null>(null);
          const [error, setError] = useState<string | null>(null);

            useEffect(() => {
                if (!userId) {
                      setError('Thiếu user_id');
                            setLoading(false);
                                  return;
                                      }

                                          const fetchCode = async () => {
                                                try {
                                                        const res = await fetch('/api/get-code', {
                                                                  method: 'POST',
                                                                            headers: { 'Content-Type': 'application/json' },
                                                                                      body: JSON.stringify({ userId }),
                                                                                              });
                                                                                                      const data = await res.json();
                                                                                                              if (!res.ok) {
                                                                                                                        setError(data.error || 'Lỗi khi lấy mã');
                                                                                                                                } else {
                                                                                                                                          setCode(data.code);
                                                                                                                                                  }
                                                                                                                                                        } catch (err) {
                                                                                                                                                                setError('Lỗi kết nối');
                                                                                                                                                                      } finally {
                                                                                                                                                                              setLoading(false);
                                                                                                                                                                                    }
                                                                                                                                                                                        };

                                                                                                                                                                                            fetchCode();
                                                                                                                                                                                              }, [userId]);

                                                                                                                                                                                                const copyCode = () => {
                                                                                                                                                                                                    if (code) {
                                                                                                                                                                                                          navigator.clipboard.writeText(code);
                                                                                                                                                                                                                alert('Đã sao chép mã!');
                                                                                                                                                                                                                    }
                                                                                                                                                                                                                      };

                                                                                                                                                                                                                        if (loading) {
                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                  <div className="min-h-screen flex flex-col items-center justify-center bg-gray-50">
                                                                                                                                                                                                                                          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
                                                                                                                                                                                                                                                  <p className="mt-4 text-gray-600">Đang xác thực hệ thống và khởi tạo mã, vui lòng chờ trong giây lát...</p>
                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                if (error) {
                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                          <div className="min-h-screen flex items-center justify-center bg-gray-50">
                                                                                                                                                                                                                                                                                  <div className="bg-white p-8 rounded-lg shadow-lg">
                                                                                                                                                                                                                                                                                            <p className="text-red-600 font-semibold">{error}</p>
                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                                                                                      <div className="min-h-screen flex flex-col items-center justify-center bg-gray-50 p-4">
                                                                                                                                                                                                                                                                                                                            <div className="bg-white rounded-lg shadow-lg p-8 max-w-md w-full">
                                                                                                                                                                                                                                                                                                                                    <h1 className="text-2xl font-bold text-center text-gray-800 mb-4">
                                                                                                                                                                                                                                                                                                                                              Mã xác thực của bạn
                                                                                                                                                                                                                                                                                                                                                      </h1>
                                                                                                                                                                                                                                                                                                                                                              <div className="bg-blue-50 border border-blue-200 rounded-md p-4 text-center">
                                                                                                                                                                                                                                                                                                                                                                        <p className="text-3xl font-mono font-bold text-blue-700">{code}</p>
                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                  onClick={copyCode}
                                                                                                                                                                                                                                                                                                                                                                                                            className="mt-4 w-full bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded"
                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                              Sao Chép Mã
                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="mt-4 text-sm text-gray-600 text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                        Hãy copy mã này và dán vào câu hỏi duyệt tham gia nhóm Zalo của bạn.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export default function GetCodePage() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Suspense fallback={<div>Loading...</div>}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <GetCodeContent />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Suspense>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }